name: Build CPU

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-13 libfftw3-dev

    - name: Build Project
      run: cmake -B build -S . --fresh -DBUILD_ARCH=cpu -DPRECISION=fp32 -DSFML=OFF && cmake --build build -j4 --config Release
